Construx.App/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Construx.App.Data;
using Construx.App.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Construx.App.Constants;
using Construx.App.Dtos.Company;
using Mapster;
using MediatR;
using Construx.App.Interfaces;
using Microsoft.AspNetCore.Identity;
using Construx.App.Domain.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;

using Microsoft.AspNetCore.Http;

namespace Construx.App.Controllers
{
    public class PhotosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPhotoRepository _photoRepository;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PhotosController(ApplicationDbContext context, IPhotoRepository photoRepository, UserManager<User> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _photoRepository = photoRepository;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Photos
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Photos.Include(p => p.ObjectType).Include(p => p.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Photos/Details/5
        [Authorize(Roles = UserRoles.Admin)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .Include(p => p.ObjectType)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photo == null || (photo.User.UserName != User.Identity.Name && !User.IsInRole(UserRoles.Admin)))
            {
                return NotFound();
            }

            return View(photo);
        }

        // GET: Photos/Create
        public IActionResult Create()
        {
            ViewData["ObjectTypeId"] = new SelectList(_context.ObjectTypes, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .Include(p => p.ObjectType)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (photo == null || (photo.User.UserName != User.Identity.Name && !User.IsInRole(UserRoles.Admin)))
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await DeletePhoto(id);
            return LocalRedirect("~/Plans/");
        }

        private bool PhotoExists(int id)
        {
            return _context.Photos.Any(e => e.Id == id);
        }

        public async Task DeletePhoto(int id)
        {
            var photo = await _context.Photos.FindAsync(id);

            string wwwRootPath = _webHostEnvironment.WebRootPath;
            var path = wwwRootPath + photo.Name;

            if (System.IO.File.Exists(path))
                System.IO.File.Delete(path);
            _context.Photos.Remove(photo);
            await _context.SaveChangesAsync();
        }
    }
}

Construx.App/Controllers/PlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Construx.App.Data;
using Construx.App.Domain.Entities;
using Construx.App.Interfaces;
using Microsoft.AspNetCore.Identity;
using Construx.App.Domain.Identity;
using Construx.App.Constants;
using Microsoft.AspNetCore.Authorization;

namespace Construx.App.Controllers
{
    public class PlansController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPlanRepository _planRepository;
        private readonly IPlanPartRepository _planPartRepository;
        private readonly UserManager<User> _userManager;
        private readonly IGenericRepository<PlanPartStatus> _planPartStatusRepository;

        public PlansController(ApplicationDbContext context, IPlanRepository planRepository, IPlanPartRepository planPartRepository, UserManager<User> userManager, IGenericRepository<PlanPartStatus> planPartStatusRepository)
        {
            _context = context;
            _planRepository = planRepository;
            _planPartRepository = planPartRepository;
            _userManager = userManager;
            _planPartStatusRepository = planPartStatusRepository;
        }
        [Authorize(Roles = UserRoles.User)]
        // GET: Plans
        public async Task<IActionResult> Index()
        {
            var plans = await _planRepository.GetPlansForUserName(User.Identity.Name);
            return View(plans);
        }
        [Authorize(Roles = UserRoles.User)]
        // GET: Plans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plan == null || plan.User.UserName != User.Identity.Name)
            {
                return NotFound();
            }
            ViewData["PlanParts"] = await _planPartRepository.GetPlanPartsForPlanId(id.Value);
            return View(plan);
        }
        [Authorize(Roles = UserRoles.User)]
        // GET: Plans/Create
        public async Task<IActionResult> Create()
        {
            ViewData["UserId"] = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
            return View();
        }
        [Authorize(Roles = UserRoles.User)]
        // POST: Plans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Name,Description")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(plan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
            return View(plan);
        }
        [Authorize(Roles = UserRoles.User)]
        // GET: Plans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["PlanPartStatuses"] = new SelectList(await _planPartStatusRepository.GetAll(), "Id", "Name");

            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans.FindAsync(id);
            if (plan == null || plan.User.UserName != User.Identity.Name)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users.Where(u => u.UserName.Equals(User.Identity.Name)), "Id", "UserName");
            return View(plan);
        }
        [Authorize(Roles = UserRoles.User)]
        // POST: Plans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Name,Description,Id")] Plan plan)
        {
            ViewData["PlanPartStatuses"] = new SelectList(await _planPartStatusRepository.GetAll(), "Id", "Name");

            if (id != plan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(plan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanExists(plan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", plan.UserId);
            return View(plan);
        }
        [Authorize(Roles = UserRoles.User)]
        [HttpPost, ActionName("CreatePlanPart")]
        public async Task<IActionResult> CreatePlanPart(int id, string name, string description, DateTime fromDate, DateTime toDate, int priority, int planPartStatusId)
        {
            PlanPart planPart = new PlanPart
            {
                PlanId = id,
                Name = name,
                Description = description,
                FromDate = fromDate,
                ToDate = toDate,
                Priority = priority,
                StatusId = planPartStatusId
            };

            _planPartRepository.Add(planPart);
            await _planPartRepository.SaveChangesAsync();

            return LocalRedirect($"~/Plans/Details/{id}");
        }
        [Authorize(Roles = UserRoles.User)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plan == null || plan.User.UserName != User.Identity.Name)
            {
                return NotFound();
            }

            return View(plan);
        }
        [Authorize(Roles = UserRoles.User)]
        // POST: Plans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plan = await _context.Plans.FindAsync(id);
            _context.Plans.Remove(plan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanExists(int id)
        {
            return _context.Plans.Any(e => e.Id == id);
        }
    }
}

Construx.App/Views/PlanParts/Create.cshtml
@model Construx.App.Domain.Entities.PlanPart

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PlanPart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FromDate" class="control-label"></label>
                <input asp-for="FromDate" class="form-control" type="date" />
                <span asp-validation-for="FromDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDate" class="control-label"></label>
                <input asp-for="ToDate" class="form-control" type="date" />
                <span asp-validation-for="ToDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.Status"></select>
            </div>
            <div class="form-group">
                <label asp-for="Plan" class="control-label"></label>
                <select asp-for="PlanId" class="form-control" asp-items="ViewBag.Plan"></select>
            </div>
            @if (ViewBag.Service != null)
            {
                <div class="form-group">
                    <label asp-for="Service" class="control-label"></label>
                    <select asp-for="ServiceId" class="form-control" asp-items="ViewBag.Service"></select>
                </div>
            }
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" min="1" max="3"/>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            @if (ViewBag.Service == null)
            {
                <div class="form-group">
                    <input type="submit" value="Create and look for services" class="btn btn-primary" />
                </div>
            }
            else
            {
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            }
        </form>
    </div>
</div>

<div>
    <a asp-controller="Plans" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Construx.App/Views/PlanParts/Delete.cshtml
@model Construx.App.Domain.Entities.PlanPart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlanPart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FromDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ToDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ToDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plan.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Service)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Service.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Construx.App/Views/PlanParts/Details.cshtml
@model Construx.App.Domain.Entities.PlanPart

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.Name</h1>
<h3>Plan: @Model.Plan.Name</h3>

<div>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>
        <dd class="col-sm-10">
            @Model.FromDate.ToString("dd-MM-yyy")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ToDate)
        </dt>
        <dd class="col-sm-10">
            @Model.ToDate.ToString("dd-MM-yyy")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Service)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Service.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>

<div class="d-flex justify-content-between">
    <h3>Gallery:</h3>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-controller="Plans" asp-action="Details" asp-route-id="@Model.PlanId">Back to List</a>
    </div>
</div>

<div class="alert alert-info">Click on the image to view full or delete.</div>

<div class="bg-gray rounded-lg d-flex flex-wrap w-100">
    @if (ViewBag.HasPhotos)
    {
        @foreach (var photo in ViewBag.photos)
        {
            <a asp-controller="Photos" asp-action="Delete" asp-route-id="@photo.Id"><img src="@photo.Name" class="shadow-sm p-2" style="width:370px; height:370px; object-fit:cover;"/></a>

        }
    }
</div>

Construx.App/Views/PlanParts/Edit.cshtml
@model Construx.App.Domain.Entities.PlanPart

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PlanPart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FromDate" class="control-label"></label>
                <input asp-for="FromDate" class="form-control" type="date" />
                <span asp-validation-for="FromDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToDate" class="control-label"></label>
                <input asp-for="ToDate" class="form-control" type="date" />
                <span asp-validation-for="ToDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlanId" class="control-label"></label>
                <select asp-for="PlanId" class="form-control" asp-items="ViewBag.PlanId"></select>
                <span asp-validation-for="PlanId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceId" class="control-label"></label>
                <select asp-for="ServiceId" class="form-control" asp-items="ViewBag.ServiceId"></select>
                <span asp-validation-for="ServiceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <input asp-for="Priority" class="form-control" min="1" max="3" />
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group form-check">
                <label class="form-check-label"> Upload Photo </label>
                <input type="file" name="file" accept="image/*" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Plans" asp-action="Details" asp-route-id="@Model.PlanId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}